### ISSUE TITLE
user-can-search-for-a-band-musician-or-album

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/dat-band#1]
## 🕹️ Functionality 

User can select from a radio group (`band`, `album` or `musician`), type in a search bar and press a search button.

## ✅ Task List

- [x] Create Navbar component:
  - [x] Within index.html, link font-awesome and bootstrap to the head element.
  - [x] Within the app.jsx render method, return the Navbar component.
  - [x] Create a navbar.jsx file, import `React`. Create a Navbar class and export it. Define the render method.
  - [x] Decide on a color scheme and a Google Font for the logo. Create a simple Navbar with a logo with an `a` tag surrounding it. Make sure it is responsive and stretches across the page.
- [x] Create a SearchForm component:
  - [x] Create a search-form.jsx file, import `React`. Create a SearchForm class and export it.
  - [x] Within app.jsx, import SearchForm and return the SearchForm in the render method.
  - [x] Within search-form.jsx, create a radio input for `band`, `album` and `musician`. Create the `label` and `input` text element for the Search Form.
  - [x] Define the constructor function and state object.
  - [x] Store the inputed information in an object and assign it to the state object.
