### ISSUE TITLE
user-can-be-redirected-within-the-pages

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/dat-band#10]
## 🕹️ Functionality

User can go from one pago to another using the links in each page.

## ✅ Task List

- [x] Add an `a` tag to each `link` element in the `BandPage` component. Add the `id` to the `href` attribute.
- [x] Add an `a` tag to each `link` element in the `AlbumPage` component. Add the `id` to the `href` attribute.
- [x] Add an `a` tag to each `link` element in the `MusicianPage` component. Add the `id` to the `href` attribute.
- [x] Style the `a` tag to a lighter link color.
