### ISSUE TITLE
user-can-see-a-dropdown-menu-while-typing-in-the-search-bar

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/dat-band#2]
## 🕹️ Functionality 

As the user is typing in the search bar, they will see results that match what they have typed in.

## ✅ Task List

- [x] Create a data.sql file with the database information for Metallica and Megadeth, including albums, past/current members, etc.
- [x] Within `App` create a method to get the values from `SearchForm`. 
- [x] Create the client-error.js file and create (and export) the ClientError class. 
- [x] Create the error-middleware.js file and create (and export) the errorMiddleware function. Also require the ClientError.
- [x] Set the app.get endpoint to search the database using the `category` and `search` params. Setup the endpoint to check for and throw errors if necessary.
- [x] Add a `fetch` request to `getParameters()` method.
- [x] Within `SearchForm`, add the returned data to state object.
- [x] Create the DropdownMenu component to render the retuned data.
- [x] Render the component with the returned data.
- [x] Use map() to render a result for each returned data in the data array.
- [x] Set a max of 5 results to be rendered.
- [x] Refactor the map() method to render information according to the state.category.
- [x] Refactor the sql to get data for album and musician.
