### ISSUE TITLE
issue-11-dropdown-menu-no-match-message

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/dat-band#21]
## 🕹️ Functionality 

User will see a `no match message` in the Dropdown Menu if there ins't a result that matches the user's search input.

## ✅ Task List

- [x] Create a `NoMatchMessage` component.
- [x] Add the `NoMatchMessage` component to the `DropdownMenu` component.
- [x] If the `DropdownMenu` props.result.data is an empty array, render the `NoMatchMessage` component.
- [x] Add `this.props.result` as a prop to `NoMatchComponent` and display the search criteria to message.
- [x] Style the `NoMatchMessage` component.
