### ISSUE TITLE
issue-12-dropdown-menu-no-category-selected-message

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/dat-band#23]
## 🕹️ Functionality

User will get a message if search bar has an input but no category was selected.

## ✅ Task List

- [x] Create a `NoCategorySelectedMessage` component.
- [x] Add the `NoCategorySelectedMessage` component to the `SearchForm` component.
- [x] Within the `render()` method of the `SearchForm` component, deconstruct `search` from `this.state`.
- [x] Within the `render()` method of the `SearchForm` component, if search exists but category doesn't, render the `NoCategorySelectedMessage` component.
- [x] Style the `NoCategorySelectedMessage` component.
