### ISSUE TITLE
issue-13-app-responsiveness

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/dat-band#25]
## 🕹️  Functionality

User will see a fully responsive app.

## ✅ Task List

- [x] Refactor the `SearchForm` component to be responsive.
- [x] Refactor the `DropdownMenu` component to be responsive.
- [x] Refactor the `BandPage` component to be responsive.
- [x] Refactor the `AlbumPage` component to be responsive.
- [x] Refactor the `MusicianPage` component to be responsive.
- [x] Refactor the message components to be responsive.
- [x] Add `alt` to the images.
- [x] Fix bugs and remove unused CSS classses.
