### ISSUE TITLE
issue-15-user-can-see-a-context-section

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/dat-band#29]
## 🕹️ Functionality

User can see a context text explaining how the app works and what to expect.

## ✅ Task List

- [x] Add a `p` tag to the `return` statement in the `render()` method of the `SearchForm` component.
- [x] Make the `p` tag responsive on all device.
- [x] Add a list of the current bands in the database.
