### ISSUE TITLE
issue-18-fix-routing-bug

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/dat-band#34]
## 🕹️ Functionality

User will get an error page if the hash route is changed to an non existing route.

## ✅ Task List

- [x] Add a `ClientError` to the first `then.` method of each endpoint if `result.rows[0]` not not exist.
- [x] Create a `NotFound` component so the user will know that the requested page doesn't exist.
- [x] Import the `NotFound` component to the `BandPage`, `AlbumPage` and `MusicianPage` component.
- [x] Within the `page()` method of the `BandPage`, `AlbumPage` and `MusicianPage` component, check if `data.error` exists. If so, return the `NotFound` component.
