### ISSUE TITLE
user-can-see-the-band-page

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/dat-band#4]
## 🕹️ Functionality 

User can click on a band result from the search and be redirected to the band's page.

## ✅ Task List
- [x] Refactor the `bandResults` component by adding a `onClick` attribute.
- [x] Refactor the `bandResults` to include an `id` attribute with the `bandId` as the value.
- [x] Lift the state from `bandResult` component to send the data to `app.jsx` once it was clicked (Obsolete).
- [x] Create a static page layout for the `BandPage` component.
- [x] Add a condicional rendering for BandPage and SearchForm.
- [x] Setup the hash routing to provide the bandId for Fetch.
- [x] Create a new fetch GET request to retrieve the data using `bandId`.
- [x] Adjust the database queries to get the data for each BandPage component.
- [x] Add the data to each component.
