### ISSUE TITLE
issue-24-show-connection-fail-alert

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/dat-band#43]
## 🕹️ Functionality 

User will see an alert there is a connection failure.

## ✅ Task List

- [x] Remove icon from the `title`.
- [x] Create an error message.
- [x] Add the error modal component to the `search-form` component.
