### ISSUE TITLE
user-can-see-a-band-image-carousel

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/dat-band#5]
## 🕹️ Functionality 

User can see a carousel of images, and go to the next and the previous image.

## ✅ Task List

- [x] Add an `imageId` to the database and update `schema.sql` and `data.sql`.
- [x] Create a `Carousel` component.
- [x] Add the `Carousel` component to the `BandPage` component.
- [x] Set the `props` to be accessed in the `Carousel` component.
- [x] Set the component's state object with the `imageIndex` property.
- [x] Create the `img` JSX element.
- [x] Create a `timer()` method.
- [x] Create a `componentDidMount` to call the `timer()` method.
- [x] Add a left and right arrow to the image using CSS `Position`.
- [x] Create a `leftClick()` method to show the next image.
- [x] Create a `rightClick()` method to show the previous image.
