### ISSUE TITLE
user-can-watch-a-youtube-video

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/dat-band#6]
## 🕹️ Functionality 

User can see and watch YouTube videos within the application.

## ✅ Task List

- [x] Create a `Videography` component.
- [x] Refactor the query to get the data from `videos`.
- [x] Make sure the videos are accessible in the `Videography` component.
- [x] Add a `iframe` JSX element and test that the video is working.
- [x] Refactor the `videoUrl` in the `schema.sql` file.
- [x] `Map` the returned data from `videos` into the `Videography` component.
