### ISSUE TITLE
user-can-see-links-to-other-band-pages

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/dat-band#7]
## 🕹️ Functionality 

User can see `links` to other bands within the `BandPage` component.

## ✅ Task List

- [x] Add more bands to the data base.
- [x] Create a static `BandSeeAlso` component.
- [x] Refactor the `index.js` file to query the database for bands that match the `bandGenre`.
- [x] Add a fetch request to the `BandSeeAlso` component.
- [x] Add the queried data to the `BandSeeAlso` component.
- [x] Add the `href` attribute to the `a` element to direct to the clicked band page.
- [x] Create a condition to check the `bandId` of the current band's page.
