### ISSUE TITLE
user-can-see-the-album-page

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/dat-band#8]
## 🕹️ Functionality 

User search for an album and see a dedicated page for the album.

## ✅ Task List

- [x] Create an `AlbumPage` component.
- [x] Add the `AlbumPage` to the `render()` method in the `App` component. Add `state` as its `props`.
- [x] Add an `a` tag with the `href` attribute to the `albumResults` method in the `DropdownMenu` component.
- [x] Create a static version of the `BandPage` component.
- [x] Within the `index.js` file, create a new endpoint to query the database for information on the album.
- [x] Create a `componentDidMount()` method with a `fetch` request using the `props` to get the `url`. Then store the returned data to `state`.
- [x] Populate the `AlbumPage` component with the data returned from the query.
- [x] Fix bugs and remove unused code.
