### ISSUE TITLE
user-can-see-the-musician-page

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/dat-band#9]
## 🕹️ Functionality

User search for a musician and see a dedicated page for the musician.

## ✅ Task List

- [x] Create a `MusicianPage` component.
- [x] Add the `MusicianPage` to the `render()` method in the `App` component.
- [x] Add an `a` JSX element to the `musicianResults()` method in the `DropdownMenu` component. Add the `href` attribute and set the value to `#musician/musicianId`.
- [x] Create a static version of the `MusicianPage` component.
  - [x] Create a `MusicianImage` component.
  - [x] Create a `MusicianTitle` component.
  - [x] Create a `MusicianInfo` component.
  - [x] Create a `MusicianAssociation` component.
  - [x] Create a `MusicianRecords` component.
- [x] Within the `index.js` file, create a new endpoint to query the database for information on the musician.
- [x] Create a `componentDidMount()` method with a `fetch` request using the `props` to get the `url`. Then store the returned data to the `state` object.
- [x] Populate the `MusicianPage` component with the queried data. Add `map()` method to the necessary components.
